---
title: "Phyloseq PreProcessing"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", fig.path = "../figures/02_PreProcessing/") # Send any figures to this folder
```

# Load libraries
```{r load-libraries}
library(devtools)
#devtools::install_github("joey711/phyloseq")
library(phyloseq)
library(tidyverse)
```

# Goals

Here, we will process the data into a phyloseq object.

- ASV table
- Taxonomy table
- Track reads (metadata)

Then, we will remove the following:

1. Remove Chloroplasts
2. Remove Mitochondria
3. Remove samples without enough reads

Finally, we will write a data file of phyloseq output

# Load data

## ASV Table
```{r load-ASV-table}
# First, load ASV table
setwd("/workdir/zlr6/gitrepos/SalinityGradient_16s")
load("data/01_DADA2/ASV_counts.RData")

# Inspect ASV table
head(asv_tab)[,1:5]

# Fix names
colnames(asv_tab)
sample_names <- colnames(asv_tab)
samples_fixed <- sapply(strsplit(basename(sample_names), "_"), `[`,1)
head(samples_fixed)

# re-write the ASV count file to fix names
colnames(asv_tab) <- samples_fixed
```

## Taxonomy Table
```{r load-tax-table}
tax_df <- read.table("data/01_DADA2/ASV_taxonomy.tsv", sep = "\t")

# fix column names
tax_df = tax_df[-1,]
colnames(tax_df) <- c("ASV", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "ASV", "ASVseq")

# Taxonomy Table Matrix
tax_df %>%
  tibble::column_to_rownames(., var = "asv_names") %>%
  as.matrix()
```

## Track Reads Data
```{r load-track-reads}

```

# Handoff
```{r phyloseq-handoff}

```